"$schema" = 'https://starship.rs/config-schema.json'

[git_branch]
style = "purple"

[gcloud]
disabled = true

[aws]
disabled = true

[kubernetes]
disabled = false
style = "bold fg:18 bg:117"

[cmd_duration]
min_time = 500
